**<h3>Movie Recommendation System Using ✨Python✨**

**<p1>Import Libraries**

In [1]:
# HAHAA IMPORT GO BRRRRR 

import numpy as np 
import pandas as pd 
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import HTML
import ipywidgets as widgets

**<p1>Colecting and proses the data**

In [2]:
# load n check movie data

pd.set_option('display.max_columns', 100)

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv') 

In [3]:
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [5]:
# combine 2 columns

merged_df = pd.merge(movies, credits, left_on='id', right_on='movie_id', how='inner', suffixes=('_movies', '_credits'))

merged_df.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                               title_movies  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
4                               John Carter           6.1        2124   

   movie_id                             title_credits  \
0     19995          

In [6]:
# select important columns

select_column = ['title_movies', 'genres', 'tagline', 'keywords', 'cast', 'production_companies']

In [7]:
# fill null values with null strings

for x in select_column : 
    merged_df[x] = merged_df[x].fillna('')

In [8]:
# merge columns 

combine_column = merged_df['title_movies'] + ' ' + merged_df['tagline'] + ' ' + merged_df['keywords']  + ' ' + merged_df['cast']  + ' ' + merged_df['production_companies'] + ' ' + merged_df['genres']

In [9]:
# convert text to numerical (feature vector)

vectorizer = TfidfVectorizer()

vector = vectorizer.fit_transform(combine_column)

print(vector)

  (0, 191527)	0.009122159525017182
  (0, 223114)	0.009059689749216764
  (0, 168522)	0.009175275575533503
  (0, 190921)	0.00970346793784514
  (0, 172550)	0.007946550553081333
  (0, 172338)	0.006912571770817927
  (0, 137337)	0.021641147148277137
  (0, 205903)	0.022084098589294346
  (0, 49879)	0.014864997138279653
  (0, 189916)	0.013370394940756078
  (0, 188701)	0.014147163806589043
  (0, 46149)	0.011631507442238353
  (0, 184511)	0.009903560108327122
  (0, 192460)	0.009415571684189378
  (0, 182003)	0.010990305225556017
  (0, 231508)	0.011593944861432079
  (0, 45589)	0.016780122029862485
  (0, 215745)	0.015150543595306824
  (0, 191625)	0.014064221052092138
  (0, 199426)	0.016780122029862485
  (0, 220023)	0.016424917758386955
  (0, 201249)	0.022084098589294346
  (0, 49399)	0.022084098589294346
  (0, 98701)	0.025240957170327375
  (0, 687)	0.012408185762343562
  :	:
  (4802, 197537)	0.07240895285371894
  (4802, 185187)	0.10220604055079198
  (4802, 197827)	0.42328144317984484
  (4802, 222222)	

**<p1>Getting Cosine Similarity**

In [10]:
# find similarity points

similarity = cosine_similarity(vector)

print(similarity)

[[1.         0.49717608 0.53780209 ... 0.32264523 0.23113064 0.31978174]
 [0.49717608 1.         0.51031902 ... 0.32466903 0.22480457 0.31708125]
 [0.53780209 0.51031902 1.         ... 0.32038543 0.2385748  0.32377677]
 ...
 [0.32264523 0.32466903 0.32038543 ... 1.         0.13711645 0.2254692 ]
 [0.23113064 0.22480457 0.2385748  ... 0.13711645 1.         0.14476025]
 [0.31978174 0.31708125 0.32377677 ... 0.2254692  0.14476025 1.        ]]


In [11]:
print(similarity.shape)

(4803, 4803)


In [12]:
# getting the movie name from the user

movie_input = input('Enter your favourite movie name : ')  # e.g : batman

In [13]:
# creating list of movie

movie_list =  merged_df['title_movies'].tolist()
print(movie_list)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [14]:
# finding the closes match of movie and index from movie input


movie_match = difflib.get_close_matches(movie_input, merged_df['title_movies'], n=1)

if movie_match:
    close_movie_title = movie_match[0]
    movie_index = (merged_df['title_movies'] == close_movie_title).idxmax()

    print("Closest match:", close_movie_title)
    print("Index of closest match:", movie_index)
else:
    print("No close match found.")

Closest match: Batman
Index of closest match: 1359


In [15]:
# getting similar movie

match_score = list(enumerate(similarity[movie_index]))

print(match_score)

[(0, 0.43802374149003687), (1, 0.44631681306176396), (2, 0.44767091756105815), (3, 0.4876467334677159), (4, 0.4094419614405181), (5, 0.46467642317206015), (6, 0.3167856307451131), (7, 0.4156596883355721), (8, 0.44527397781668765), (9, 0.5203136042882837), (10, 0.4336273185774255), (11, 0.4037398945664415), (12, 0.4474200152486683), (13, 0.47084483468857896), (14, 0.4621844818765708), (15, 0.3896275772058132), (16, 0.4445912616561888), (17, 0.4589684387410815), (18, 0.3836302345653146), (19, 0.46197490977827144), (20, 0.47372936209181465), (21, 0.42957466071086453), (22, 0.4260263112776924), (23, 0.4119626138986892), (24, 0.41439390988385827), (25, 0.49933892779946204), (26, 0.43730513353686595), (27, 0.4083213817302203), (28, 0.42427494002223665), (29, 0.3957790341689469), (30, 0.4800375753123476), (31, 0.3984559650875971), (32, 0.41202081693923265), (33, 0.4313528232234337), (34, 0.3443438537805778), (35, 0.42078434214491783), (36, 0.43748273210622557), (37, 0.33223030120021313), (38,

In [16]:
# sorting the movie based on match score 

sorted_match_movie = sorted(match_score, key= lambda x:x[1], reverse=True)

print(sorted_match_movie)

[(1359, 1.0), (65, 0.5303613555494453), (9, 0.5203136042882837), (1847, 0.5152130636632362), (72, 0.5107302408274881), (365, 0.506822082418412), (361, 0.5054866323450937), (1133, 0.5013569807940254), (119, 0.5011332281755158), (2442, 0.500924526342962), (210, 0.5008798648053503), (2024, 0.500508277569165), (1387, 0.5001469645451861), (25, 0.49933892779946204), (322, 0.49872383069789916), (813, 0.49799967292779646), (125, 0.4979677856778234), (281, 0.49714776534510446), (1432, 0.49702603788228156), (1103, 0.49685504195260716), (4216, 0.49521875998066434), (1782, 0.49521476615349697), (870, 0.4941878383309423), (3753, 0.49349272848365633), (633, 0.4934729641736813), (299, 0.493262808466845), (2123, 0.4924411496574706), (287, 0.49152159899478776), (1874, 0.49087942916088584), (1923, 0.4908705194613916), (662, 0.49074798123031377), (850, 0.49034309372542406), (1540, 0.4901466808767706), (2544, 0.48997024384090415), (1181, 0.48925457569457204), (3, 0.4876467334677159), (2627, 0.487608160428

In [17]:
# print the name of similar movies based on index

print("Movie for u : \n")

i = 1 
for movie in sorted_match_movie: 
    index = movie[0]
    title_Findex = merged_df.loc[index, 'title_movies']
    if i < 16: 
        print(i, '.', title_Findex)
        i += 1

Movie for u : 

1 . Batman
2 . The Dark Knight
3 . Batman v Superman: Dawn of Justice
4 . GoodFellas
5 . Suicide Squad
6 . Contact
7 . You Don't Mess with the Zohan
8 . 15 Minutes
9 . Batman Begins
10 . Southland Tales
11 . Batman & Robin
12 . Gandhi
13 . Malcolm X
14 . Titanic
15 . The Fifth Element


**<h3>Movie recommendation system**

<center><h3><b>Movie Recommendation System</b></h3></center>
<center><p>Movie Recommendation System using ✨Python✨ Discover your next movie night based on your favorite genres and preferences!</p></center>

In [18]:
from IPython.display import display

# function to perform movie search and display results
def search_and_display(change):
    movie_input_value = change['new']
    
    if not movie_input_value:
        # If input is empty, do nothing
        return
    
    movie_match = difflib.get_close_matches(movie_input_value, merged_df['title_movies'], n=1)

    movie_list.clear_output(wait=True)  # clear previous output

    if movie_match:
        close_movie_title = movie_match[0]
        movie_index = (merged_df['title_movies'] == close_movie_title).idxmax()

        with movie_list:
            match_score = list(enumerate(similarity[movie_index]))
            sorted_match_movie = sorted(match_score, key=lambda x: x[1], reverse=True)

            print("Movies for you : \n")
            i = 1
            for movie in sorted_match_movie:
                index = movie[0]
                title_Findex = merged_df.loc[index, 'title_movies']
                if i < 16:
                    print(i, '.', title_Findex)
                    i += 1
    else:
        # do nothing if no match is found
        pass

# create input widget
movie_input = widgets.Text(
    description="Movie Title :",
    placeholder="Type ur fav movie here!",
    disabled=False,
    layout=widgets.Layout(width='50%')
)

# create output widget
movie_list = widgets.Output()

movie_input.observe(search_and_display, names='value')
display(movie_input, movie_list)

Text(value='', description='Movie Title :', layout=Layout(width='50%'), placeholder='Type ur fav movie here!')

Output()